### ISSUE TITLE
Revit_Toolkit: Move methods not referencing Revit API to BH.Engine.Adapters.Revit

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#457]
#### Description:
Some methods that do not reference Revit API sit in `BH.UI.Revit.Engine` - they could be moved to `BH.Engine.Adapters.Revit`:
- [ ] BH.UI.Revit.Engine.Query.Discipline - to be merged with `BH.Engine.Adapters.Revit.Query.Discipline`
- [x] BH.UI.Revit.Engine.Query.UpdatePanelTypeByCustomData - to be handled in #461 
- [x] BH.UI.Revit.Engine.Query.LowElevation - to be handled in #446
- [x] BH.UI.Revit.Engine.Query.HighElevation - to be handled in #446

**Comment by FraserGreenroyd** [comment]
Should they have `Adapters` in the namespace at all? I can't remember what the decision was on that?

**Comment by pawelbaran** [comment]
I do not think we made an agreement on that. Personally I have no opinion: as long as everything works, the name can be anything.
